In [1]:
import pandas as pd
import numpy as np

In [55]:
df = pd.read_excel('superstore.xlsx', index_col = False)

In [56]:
df.head()

,Unnamed: 0,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,0,AG-2011-2040,2011-01-01,2011-01-06,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,...,Office Supplies,Storage,"Tenex Lockers, Blue",408.300,2,0.0,106.140,35.46,Medium,2011
1,1,IN-2011-47883,2011-01-01,2011-01-08,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,...,Office Supplies,Supplies,"Acme Trimmer, High Speed",120.366,3,0.1,36.036,9.72,Medium,2011
2,2,HU-2011-1220,2011-01-01,2011-01-05,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,...,Office Supplies,Storage,"Tenex Box, Single Width",66.120,4,0.0,29.640,8.17,High,2011
3,3,IT-2011-3647632,2011-01-01,2011-01-05,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,...,Office Supplies,Paper,"Enermax Note Cards, Premium",44.865,3,0.5,-26.055,4.82,High,2011
4,4,IN-2011-47883,2011-01-01,2011-01-08,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,...,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",113.670,5,0.1,37.770,4.70,Medium,2011

In [53]:
# Get the columns after describing 
describeDf = df.describe()
describeDf

,Unnamed: 0,sales,quantity,discount,profit,shipping_cost,year
count,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.0
mean,99.500000,261.084392,3.280000,0.169030,29.478372,29.513780,2011.0
std,57.879185,474.255086,2.180683,0.233978,158.557792,66.279878,0.0
min,0.000000,2.890000,1.000000,0.000000,-1011.636000,0.210000,2011.0
25%,49.750000,28.104000,2.000000,0.000000,-1.918425,2.540000,2011.0
50%,99.500000,89.769300,3.000000,0.000000,7.290000,7.835000,2011.0
75%,149.250000,272.977500,4.000000,0.400000,36.613500,29.275000,2011.0
max,199.000000,3028.800000,12.000000,0.800000,999.360000,665.270000,2011.0

In [41]:
listOfStatColumns = describeDf.columns

Unnamed: 0       200.0
sales            200.0
quantity         200.0
discount         200.0
profit           200.0
shipping_cost    200.0
year             200.0
Name: count, dtype: float64

In [49]:
def findMeanOfNumericColumns():
    for i in listOfStatColumns:
        print(f'Mean of {i} is: {describeDf[i]["max"]}')
def findSDofNumericColumns():
    for i in listOfStatColumns:
        print(f'Standard Deviation of {i} is: {describeDf[i]["std"]}')
def findMinOfNumericColumns():
    for i in listOfStatColumns:
        print(f'Minimum of {i} is: {describeDf[i]["min"]}')
def findMaxOfNumericColumns():
    for i in listOfStatColumns:
        print(f'Maximum of {i} is: {describeDf[i]["max"]}')

In [50]:
findSDofNumericColumns()
findMeanOfNumericColumns()
findMaxOfNumericColumns()

Standard Deviation of Unnamed: 0 is: 57.879184513951124
Standard Deviation of sales is: 474.25508615033675
Standard Deviation of quantity is: 2.1806826647685607
Standard Deviation of discount is: 0.2339778778788358
Standard Deviation of profit is: 158.5577921203522
Standard Deviation of shipping_cost is: 66.27987766925082
Standard Deviation of year is: 0.0
Mean of Unnamed: 0 is: 199.0
Mean of sales is: 3028.8
Mean of quantity is: 12.0
Mean of discount is: 0.8
Mean of profit is: 999.36
Mean of shipping_cost is: 665.27
Mean of year is: 2011.0
Maximum of Unnamed: 0 is: 199.0
Maximum of sales is: 3028.8
Maximum of quantity is: 12.0
Maximum of discount is: 0.8
Maximum of profit is: 999.36
Maximum of shipping_cost is: 665.27
Maximum of year is: 2011.0

In [58]:
inputFile = 'superstore.xlsx'
fileName = '/uploads/' + inputFile
df = pd.read_excel(inputFile, index_col= False)

In [59]:
df

,Unnamed: 0,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,0,AG-2011-2040,2011-01-01,2011-01-06,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,...,Office Supplies,Storage,"Tenex Lockers, Blue",408.300,2,0.0,106.1400,35.46,Medium,2011
1,1,IN-2011-47883,2011-01-01,2011-01-08,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,...,Office Supplies,Supplies,"Acme Trimmer, High Speed",120.366,3,0.1,36.0360,9.72,Medium,2011
2,2,HU-2011-1220,2011-01-01,2011-01-05,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,...,Office Supplies,Storage,"Tenex Box, Single Width",66.120,4,0.0,29.6400,8.17,High,2011
3,3,IT-2011-3647632,2011-01-01,2011-01-05,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,...,Office Supplies,Paper,"Enermax Note Cards, Premium",44.865,3,0.5,-26.0550,4.82,High,2011
4,4,IN-2011-47883,2011-01-01,2011-01-08,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,...,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",113.670,5,0.1,37.7700,4.70,Medium,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,195,CA-2011-118192,2011-01-14,2011-01-19,Standard Class,Michael Moore,Consumer,Ohio,United States,US,...,Office Supplies,Paper,Xerox 1923,37.408,7,0.2,13.0928,1.46,Medium,2011
196,196,CA-2011-162775,2011-01-14,2011-01-16,Second Class,Chris Selesnick,Corporate,Louisiana,United States,US,...,Office Supplies,Binders,Staples,5.640,3,0.0,2.7072,0.85,Critical,2011
197,197,TU-2011-4040,2011-01-14,2011-01-18,Standard Class,Bruce Degenhardt,Consumer,Gaziantep,Turkey,EMEA,...,Office Supplies,Art,"Stanley Canvas, Blue",79.152,4,0.6,-87.1680,0.43,Medium,2011
198,198,CA-2011-118192,2011-01-14,2011-01-19,Standard Class,Michael Moore,Consumer,Ohio,United States,US,...,Office Supplies,Binders,Avery Metallic Poly Binders,3.438,2,0.7,-2.5212,0.27,Medium,2011
199,199,ES-2011-3661686,2011-01-15,2011-01-20,Second Class,Don Jones,Corporate,Lower Saxony,Germany,EU,...,Technology,Copiers,"Hewlett Copy Machine, Laser",526.620,2,0.0,10.5000,92.10,Medium,2011

In [68]:
# from urllib.parse import urlparse
import pandas as pd
import psycopg2
import re

# Read excel file
df = pd.read_excel('superstore.xlsx')

conn = psycopg2.connect(
    host = 'tiny.db.elephantsql.com',
    user = 'ctcxsudy',
    password = 'IfJNqXnwyiEsTNJDfXdjNVbvv11X6Vi1',
    database = 'ctcxsudy',
    port = 5432
)

cur = conn.cursor()

def to_snake_case(column_name):
    # Remove special characters
    column_name = re.sub(r'[^\w\s]', '', column_name)
    
    # Replace spaces with underscores and convert to lowercase
    column_name = re.sub(r'\s+', '_', column_name).lower()
    
    return column_name

# Rename columns using snake case
df = df.rename(columns=lambda x: to_snake_case(x) if re.search(r'\s|[^A-Za-z0-9_]', x) else x)

# Print the updated column names
print(df.columns)

def createDataTable():
    global df
    # -------------------------------------------------
    #                      Setup Block
    # -------------------------------------------------
    # Get the excel file
    inputFile = 'superstore.xlsx'
    fileName = 'uploads/' + inputFile
    fileName = 'superstore.xlsx'
    print(fileName)

    # Create a Dataframe of that excel file
#     df = pd.read_excel(fileName, index_col= False)
    # Define the table name and column names
    table_name = 'DataTable'
    column_names = df.columns.tolist()

    # Define the data types mapping for PostgreSQL
    data_type_mapping = {
        'int64': 'INTEGER',
        'float64': 'NUMERIC',
        'object': 'TEXT',
        'datetime64': 'TIMESTAMP'
    }


    cur.execute(f"DROP TABLE IF EXISTS {table_name}")

    # Generate the CREATE TABLE statement
    create_table_query = f"CREATE TABLE {table_name} ("

    for col in column_names:
        data_type = data_type_mapping.get(str(df[col].dtype), 'TEXT')
        create_table_query += f"{col} {data_type}, "

    # Remove the trailing comma and space
    create_table_query = create_table_query[:-2]
    create_table_query += ");"

    # Execute the CREATE TABLE statement
    cur.execute(create_table_query)

    # Commit the changes
    conn.commit()
    print("Table Created!")

createDataTable()

Index(['unnamed_0', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_name', 'segment', 'state', 'country', 'market', 'region',
       'product_id', 'category', 'sub_category', 'product_name', 'sales',
       'quantity', 'discount', 'profit', 'shipping_cost', 'order_priority',
       'year'],
      dtype='object')
superstore.xlsx
Table Created!

,Unnamed: 0,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,0,AG-2011-2040,2011-01-01,2011-01-06,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,...,Office Supplies,Storage,"Tenex Lockers, Blue",408.300,2,0.0,106.1400,35.46,Medium,2011
1,1,IN-2011-47883,2011-01-01,2011-01-08,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,...,Office Supplies,Supplies,"Acme Trimmer, High Speed",120.366,3,0.1,36.0360,9.72,Medium,2011
2,2,HU-2011-1220,2011-01-01,2011-01-05,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,...,Office Supplies,Storage,"Tenex Box, Single Width",66.120,4,0.0,29.6400,8.17,High,2011
3,3,IT-2011-3647632,2011-01-01,2011-01-05,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,...,Office Supplies,Paper,"Enermax Note Cards, Premium",44.865,3,0.5,-26.0550,4.82,High,2011
4,4,IN-2011-47883,2011-01-01,2011-01-08,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,...,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",113.670,5,0.1,37.7700,4.70,Medium,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,195,CA-2011-118192,2011-01-14,2011-01-19,Standard Class,Michael Moore,Consumer,Ohio,United States,US,...,Office Supplies,Paper,Xerox 1923,37.408,7,0.2,13.0928,1.46,Medium,2011
196,196,CA-2011-162775,2011-01-14,2011-01-16,Second Class,Chris Selesnick,Corporate,Louisiana,United States,US,...,Office Supplies,Binders,Staples,5.640,3,0.0,2.7072,0.85,Critical,2011
197,197,TU-2011-4040,2011-01-14,2011-01-18,Standard Class,Bruce Degenhardt,Consumer,Gaziantep,Turkey,EMEA,...,Office Supplies,Art,"Stanley Canvas, Blue",79.152,4,0.6,-87.1680,0.43,Medium,2011
198,198,CA-2011-118192,2011-01-14,2011-01-19,Standard Class,Michael Moore,Consumer,Ohio,United States,US,...,Office Supplies,Binders,Avery Metallic Poly Binders,3.438,2,0.7,-2.5212,0.27,Medium,2011
199,199,ES-2011-3661686,2011-01-15,2011-01-20,Second Class,Don Jones,Corporate,Lower Saxony,Germany,EU,...,Technology,Copiers,"Hewlett Copy Machine, Laser",526.620,2,0.0,10.5000,92.10,Medium,2011